"""add: campagnes et offres routes et schemas

Revision ID: 38af88a06dc2
Revises:
Create Date: 2026-07-21 17:41:30.719563
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38af88a06dc2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidats",
        sa.Column("nom", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("mot_de_passe_hash", sa.String(length=255), nullable=True),
        sa.Column("telephone", sa.String(length=50), nullable=True),
        sa.Column("titre_principal", sa.String(length=255), nullable=True),
        sa.Column("annees_experience", sa.Integer(), nullable=True),
        sa.Column("localisation", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candidats_email"), "candidats", ["email"], unique=True)
    op.create_table(
        "entreprises",
        sa.Column("nom", sa.String(length=255), nullable=False),
        sa.Column("domaine", sa.String(length=255), nullable=True),
        sa.Column("secteur", sa.String(length=255), nullable=True),
        sa.Column("taille", sa.String(length=50), nullable=True),
        sa.Column("adresse", sa.String(length=500), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "abonnements",
        sa.Column("entreprise_id", sa.UUID(), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("starter", "business", "enterprise", name="plan_abonnement"),
            nullable=False,
        ),
        sa.Column(
            "statut", sa.Enum("actif", "expire", "essai", name="statut_abonnement"), nullable=False
        ),
        sa.Column("date_debut", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_fin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entreprise_id"], ["entreprises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entreprise_id"),
    )
    op.create_table(
        "campagnes",
        sa.Column("entreprise_id", sa.UUID(), nullable=False),
        sa.Column("intitule", sa.String(length=255), nullable=False),
        sa.Column("departement", sa.String(length=255), nullable=True),
        sa.Column("date_limite", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nombre_postes", sa.Integer(), nullable=False),
        sa.Column("localisation", sa.String(length=255), nullable=True),
        sa.Column("competences", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("experience", sa.String(length=100), nullable=True),
        sa.Column("langues", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("niveau_etudes", sa.String(length=100), nullable=True),
        sa.Column("type_contrat", sa.String(length=100), nullable=True),
        sa.Column("salaire", sa.String(length=100), nullable=True),
        sa.Column("workflow", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entreprise_id"], ["entreprises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "utilisateurs",
        sa.Column("entreprise_id", sa.UUID(), nullable=False),
        sa.Column("nom", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("mot_de_passe_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "recruteur",
                "admin_rh",
                "admin_plateforme",
                "evaluateur_technique",
                name="role_utilisateur",
            ),
            nullable=False,
        ),
        sa.Column("actif", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entreprise_id"], ["entreprises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_utilisateurs_email"), "utilisateurs", ["email"], unique=True)
    op.create_table(
        "offres",
        sa.Column("campagne_id", sa.UUID(), nullable=False),
        sa.Column("createur_id", sa.UUID(), nullable=True),
        sa.Column("titre", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "type_contrat",
            sa.Enum("CDI", "CDD", "Stage", "Alternance", "Freelance", name="type_contrat"),
            nullable=True,
        ),
        sa.Column("localisation", sa.String(length=255), nullable=True),
        sa.Column("salaire_min", sa.Integer(), nullable=True),
        sa.Column("salaire_max", sa.Integer(), nullable=True),
        sa.Column(
            "statut",
            sa.Enum("brouillon", "publiee", "archivee", name="statut_offre"),
            nullable=False,
        ),
        sa.Column("date_publication", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reception_ouverte", sa.Boolean(), nullable=False),
        sa.Column(
            "champs_personnalises_def", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campagne_id"], ["campagnes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["createur_id"], ["utilisateurs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidatures",
        sa.Column("offre_id", sa.UUID(), nullable=False),
        sa.Column("candidat_id", sa.UUID(), nullable=False),
        sa.Column(
            "statut",
            sa.Enum(
                "recue",
                "en_cours_analyse",
                "preselectionnee",
                "test_technique",
                "entretien_rh",
                "entretien_metier",
                "verification_references",
                "decision",
                "offre_envoyee",
                "embauche",
                "refusee",
                "vivier_talents",
                name="statut_candidature",
            ),
            nullable=False,
        ),
        sa.Column(
            "date_soumission",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lettre_motivation", sa.Text(), nullable=True),
        sa.Column("cv_url", sa.Text(), nullable=True),
        sa.Column("champs_personnalises", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score_global", sa.Integer(), nullable=True),
        sa.Column("evaluation_ia", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidat_id"], ["candidats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["offre_id"], ["offres.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candidatures")
    op.drop_table("offres")
    op.drop_index(op.f("ix_utilisateurs_email"), table_name="utilisateurs")
    op.drop_table("utilisateurs")
    op.drop_table("campagnes")
    op.drop_table("abonnements")
    op.drop_table("entreprises")
    op.drop_index(op.f("ix_candidats_email"), table_name="candidats")
    op.drop_table("candidats")
    # ### end Alembic commands ###
