"""rattrapage: synchronise migrations avec les modeles actuels

Revision ID: c1f0d928c5bc
Revises: 38af88a06dc2
Create Date: 2026-07-23 08:38:25.062653

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c1f0d928c5bc"
down_revision = "38af88a06dc2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE (fix manuel) : `statut_entreprise` est un type ENUM Postgres tout
    # nouveau. Pour une colonne créée avec CREATE TABLE, SQLAlchemy crée le
    # type automatiquement — mais pour un ADD COLUMN sur une table existante
    # (cas ici), il faut le créer explicitement, sinon l'ALTER TABLE plus bas
    # échoue avec `type "statut_entreprise" does not exist`.
    sa.Enum("active", "suspendue", name="statut_entreprise").create(
        op.get_bind(), checkfirst=True
    )
    op.create_table(
        "audit_logs",
        sa.Column(
            "table_name", sa.String(length=100), nullable=False, comment="Nom de la table modifiée"
        ),
        sa.Column("record_id", sa.UUID(), nullable=False, comment="ID de l'enregistrement modifié"),
        sa.Column(
            "action",
            sa.String(length=20),
            nullable=False,
            comment="Action réalisée (CREATE, UPDATE, DELETE, LOGIN, LOGOUT)",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="ID de l'utilisateur ayant réalisé l'action",
        ),
        sa.Column(
            "user_email",
            sa.String(length=255),
            nullable=True,
            comment="Email de l'utilisateur (redondant pour recherche)",
        ),
        sa.Column(
            "changes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Changements effectués (ancienne/valeur nouvelle)",
        ),
        sa.Column(
            "ip_address", sa.String(length=45), nullable=True, comment="Adresse IP de l'utilisateur"
        ),
        sa.Column(
            "user_agent",
            sa.String(length=255),
            nullable=True,
            comment="User-Agent du navigateur/client",
        ),
        sa.Column(
            "request_id",
            sa.String(length=36),
            nullable=True,
            comment="ID unique de la requête (pour traçabilité)",
        ),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Identifiant unique de l'enregistrement"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date et heure de création",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date et heure de dernière modification",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index("ix_audit_logs_record_id", "audit_logs", ["record_id"], unique=False)
    op.create_index("ix_audit_logs_table_name", "audit_logs", ["table_name"], unique=False)
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"], unique=False)
    op.add_column(
        "abonnements",
        sa.Column(
            "renouvellement_auto",
            sa.Boolean(),
            nullable=False,
            comment="Indique si l'abonnement se renouvelle automatiquement",
        ),
    )
    op.add_column(
        "abonnements",
        sa.Column(
            "derniere_renouvellement",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date du dernier renouvellement",
        ),
    )
    op.alter_column(
        "abonnements",
        "entreprise_id",
        existing_type=sa.UUID(),
        comment="ID de l'entreprise propriétaire de l'abonnement",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "plan",
        existing_type=postgresql.ENUM("starter", "business", "enterprise", name="plan_abonnement"),
        comment="Plan d'abonnement (starter, business, enterprise)",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "statut",
        existing_type=postgresql.ENUM("actif", "expire", "essai", name="statut_abonnement"),
        comment="Statut de l'abonnement (actif, expire, essai)",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "date_debut",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date de début de l'abonnement",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "date_fin",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date de fin de l'abonnement",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "id",
        existing_type=sa.UUID(),
        comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "abonnements",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "campagnes",
        sa.Column(
            "experience_requise",
            sa.String(length=100),
            nullable=True,
            comment="Expérience requise (ex: 3-5 ans)",
        ),
    )
    op.add_column(
        "campagnes",
        sa.Column("salaire_min", sa.Integer(), nullable=True, comment="Salaire minimum proposé"),
    )
    op.add_column(
        "campagnes",
        sa.Column("salaire_max", sa.Integer(), nullable=True, comment="Salaire maximum proposé"),
    )
    op.add_column(
        "campagnes",
        sa.Column(
            "recruteurs_responsables",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Liste des IDs des recruteurs responsables",
        ),
    )
    op.add_column(
        "campagnes",
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Description détaillée de la campagne"
        ),
    )
    op.add_column(
        "campagnes",
        sa.Column(
            "statut",
            sa.String(length=50),
            nullable=False,
            comment="Statut de la campagne (active, terminee, annulee)",
        ),
    )
    op.alter_column(
        "campagnes",
        "entreprise_id",
        existing_type=sa.UUID(),
        comment="ID de l'entreprise propriétaire",
        existing_nullable=False,
    )
    op.alter_column(
        "campagnes",
        "intitule",
        existing_type=sa.VARCHAR(length=255),
        comment="Intitulé de la campagne",
        existing_nullable=False,
    )
    op.alter_column(
        "campagnes",
        "departement",
        existing_type=sa.VARCHAR(length=255),
        comment="Département ou service concerné",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "date_limite",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date limite de la campagne",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "nombre_postes",
        existing_type=sa.INTEGER(),
        comment="Nombre de postes à pourvoir",
        existing_nullable=False,
    )
    op.alter_column(
        "campagnes",
        "localisation",
        existing_type=sa.VARCHAR(length=255),
        comment="Localisation du poste",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "competences",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        comment="Compétences requises",
        postgresql_using="to_jsonb(competences)",
    )
    op.alter_column(
        "campagnes",
        "langues",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        comment="Langues requises",
        postgresql_using="to_jsonb(langues)",
    )
    op.alter_column(
        "campagnes",
        "niveau_etudes",
        existing_type=sa.VARCHAR(length=100),
        comment="Niveau d'études requis",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "type_contrat",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Enum("CDI", "CDD", "Stage", "Alternance", "Freelance", name="type_contrat"),
        comment="Type de contrat proposé",
        existing_nullable=True,
        postgresql_using="type_contrat::type_contrat",
    )
    op.alter_column(
        "campagnes",
        "workflow",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Workflow personnalisé de la campagne",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "id",
        existing_type=sa.UUID(),
        comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "campagnes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "campagnes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("ix_campagnes_date_limite", "campagnes", ["date_limite"], unique=False)
    op.create_index("ix_campagnes_entreprise_id", "campagnes", ["entreprise_id"], unique=False)
    op.create_index("ix_campagnes_statut", "campagnes", ["statut"], unique=False)
    op.drop_column("campagnes", "experience")
    op.drop_column("campagnes", "salaire")
    op.add_column(
        "candidats",
        sa.Column("cv_url", sa.String(length=500), nullable=True, comment="URL du CV uploadé"),
    )
    op.add_column(
        "candidats",
        sa.Column(
            "email_verifie",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Indique si l'email a été vérifié",
        ),
    )
    op.add_column(
        "candidats",
        sa.Column(
            "linkedin_url", sa.String(length=255), nullable=True, comment="URL du profil LinkedIn"
        ),
    )
    op.add_column(
        "candidats",
        sa.Column(
            "portfolio_url", sa.String(length=255), nullable=True, comment="URL du portfolio"
        ),
    )
    op.add_column(
        "candidats",
        sa.Column(
            "disponibilite",
            sa.String(length=50),
            nullable=True,
            comment="Disponibilité (immediate, 1 mois, etc.)",
        ),
    )
    op.add_column(
        "candidats",
        sa.Column("preavis", sa.Integer(), nullable=True, comment="Durée du préavis en jours"),
    )
    op.add_column(
        "candidats",
        sa.Column(
            "pret_a_relocaliser", sa.Boolean(), nullable=False, comment="Prêt à se relocaliser"
        ),
    )
    op.add_column(
        "candidats",
        sa.Column(
            "permis_conduire", sa.Boolean(), nullable=False, comment="Possède un permis de conduire"
        ),
    )
    op.add_column(
        "candidats",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date et heure de la suppression logique",
        ),
    )
    op.add_column(
        "candidats",
        sa.Column(
            "deleted_by",
            sa.UUID(),
            nullable=True,
            comment="ID de l'utilisateur qui a effectué la suppression",
        ),
    )
    op.alter_column(
        "candidats",
        "nom",
        existing_type=sa.VARCHAR(length=255),
        comment="Nom complet du candidat",
        existing_nullable=False,
    )
    op.alter_column(
        "candidats",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Adresse email (unique)",
        existing_nullable=False,
    )
    op.alter_column(
        "candidats",
        "mot_de_passe_hash",
        existing_type=sa.VARCHAR(length=255),
        comment="Hash du mot de passe (null si pas de compte)",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "telephone",
        existing_type=sa.VARCHAR(length=50),
        comment="Numéro de téléphone",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "titre_principal",
        existing_type=sa.VARCHAR(length=255),
        comment="Titre ou poste actuel",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "annees_experience",
        existing_type=sa.INTEGER(),
        comment="Nombre d'années d'expérience",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "localisation",
        existing_type=sa.VARCHAR(length=255),
        comment="Localisation géographique",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "id",
        existing_type=sa.UUID(),
        comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "candidats",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "candidats",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "ix_candidats_email_verifie", "candidats", ["email", "email_verifie"], unique=False
    )
    op.create_index("ix_candidats_nom", "candidats", ["nom"], unique=False)
    op.add_column(
        "candidatures",
        sa.Column(
            "date_analyse",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date d'analyse de la candidature",
        ),
    )
    op.add_column(
        "candidatures",
        sa.Column(
            "commentaires",
            sa.Text(),
            nullable=True,
            comment="Commentaires généraux sur la candidature",
        ),
    )
    op.add_column(
        "candidatures",
        sa.Column(
            "evaluation_technique",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Évaluation technique du candidat",
        ),
    )
    op.add_column(
        "candidatures",
        sa.Column(
            "entretien_notes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Notes d'entretien",
        ),
    )
    op.add_column(
        "candidatures",
        sa.Column(
            "decision_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date de la décision finale",
        ),
    )
    op.add_column(
        "candidatures",
        sa.Column(
            "motif_refus", sa.Text(), nullable=True, comment="Motif du refus (si applicable)"
        ),
    )
    op.alter_column(
        "candidatures",
        "offre_id",
        existing_type=sa.UUID(),
        comment="ID de l'offre associée",
        existing_nullable=False,
    )
    op.alter_column(
        "candidatures",
        "candidat_id",
        existing_type=sa.UUID(),
        comment="ID du candidat associé",
        existing_nullable=False,
    )
    op.alter_column(
        "candidatures",
        "statut",
        existing_type=postgresql.ENUM(
            "recue",
            "en_cours_analyse",
            "preselectionnee",
            "test_technique",
            "entretien_rh",
            "entretien_metier",
            "verification_references",
            "decision",
            "offre_envoyee",
            "embauche",
            "refusee",
            "vivier_talents",
            name="statut_candidature",
        ),
        comment="Statut actuel de la candidature",
        existing_nullable=False,
    )
    op.alter_column(
        "candidatures",
        "date_soumission",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de soumission",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "candidatures",
        "lettre_motivation",
        existing_type=sa.TEXT(),
        comment="Lettre de motivation du candidat",
        existing_nullable=True,
    )
    op.alter_column(
        "candidatures",
        "cv_url",
        existing_type=sa.TEXT(),
        comment="URL du CV du candidat",
        existing_nullable=True,
    )
    op.alter_column(
        "candidatures",
        "champs_personnalises",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Réponses aux champs personnalisés",
        existing_nullable=False,
    )
    op.alter_column(
        "candidatures",
        "score_global",
        existing_type=sa.INTEGER(),
        comment="Score global calculé par l'IA (0-100)",
        existing_nullable=True,
    )
    op.alter_column(
        "candidatures",
        "evaluation_ia",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Évaluation détaillée générée par l'IA",
        existing_nullable=True,
    )
    op.alter_column(
        "candidatures",
        "id",
        existing_type=sa.UUID(),
        comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "candidatures",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "candidatures",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("ix_candidatures_candidat_id", "candidatures", ["candidat_id"], unique=False)
    op.create_index(
        "ix_candidatures_date_soumission", "candidatures", ["date_soumission"], unique=False
    )
    op.create_index("ix_candidatures_offre_id", "candidatures", ["offre_id"], unique=False)
    op.create_index("ix_candidatures_statut", "candidatures", ["statut"], unique=False)
    op.add_column(
        "entreprises",
        sa.Column(
            "site_web", sa.String(length=255), nullable=True, comment="Site web de l'entreprise"
        ),
    )
    op.add_column(
        "entreprises",
        sa.Column("telephone", sa.String(length=50), nullable=True, comment="Numéro de téléphone"),
    )
    op.add_column(
        "entreprises",
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=True,
            comment="Description de l'entreprise",
        ),
    )
    op.add_column(
        "entreprises",
        sa.Column(
            "statut",
            sa.Enum("active", "suspendue", name="statut_entreprise"),
            server_default="active",
            nullable=False,
            comment="Statut de l'entreprise (active, suspendue)",
        ),
    )
    op.add_column(
        "entreprises",
        sa.Column(
            "motif_suspension",
            sa.String(length=500),
            nullable=True,
            comment="Motif de la suspension (si applicable)",
        ),
    )
    op.alter_column(
        "entreprises",
        "nom",
        existing_type=sa.VARCHAR(length=255),
        comment="Nom de l'entreprise",
        existing_nullable=False,
    )
    op.alter_column(
        "entreprises",
        "domaine",
        existing_type=sa.VARCHAR(length=255),
        comment="Domaine d'activité",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "secteur",
        existing_type=sa.VARCHAR(length=255),
        comment="Secteur d'activité",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "taille",
        existing_type=sa.VARCHAR(length=50),
        comment="Taille de l'entreprise (PME, Grand Groupe, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "adresse",
        existing_type=sa.VARCHAR(length=500),
        comment="Adresse de l'entreprise",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "logo_url",
        existing_type=sa.VARCHAR(length=500),
        comment="URL du logo de l'entreprise",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "id",
        existing_type=sa.UUID(),
        comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "entreprises",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "entreprises",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("ix_entreprises_nom", "entreprises", ["nom"], unique=False)
    op.create_index("ix_entreprises_statut", "entreprises", ["statut"], unique=False)
    op.add_column(
        "offres",
        sa.Column(
            "missions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Liste des missions principales",
        ),
    )
    op.add_column(
        "offres",
        sa.Column(
            "soft_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Compétences comportementales requises",
        ),
    )
    op.add_column(
        "offres",
        sa.Column(
            "avantages",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Avantages proposés",
        ),
    )
    op.add_column(
        "offres",
        sa.Column(
            "tele_travail",
            sa.String(length=50),
            nullable=True,
            comment="Télétravail : full, partial, no",
        ),
    )
    op.add_column(
        "offres",
        sa.Column(
            "visible",
            sa.Boolean(),
            nullable=False,
            comment="Indique si l'offre est visible publiquement",
        ),
    )
    op.alter_column(
        "offres",
        "campagne_id",
        existing_type=sa.UUID(),
        comment="ID de la campagne associée",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "createur_id",
        existing_type=sa.UUID(),
        comment="ID de l'utilisateur créateur",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "titre",
        existing_type=sa.VARCHAR(length=255),
        comment="Titre de l'offre d'emploi",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "description",
        existing_type=sa.TEXT(),
        comment="Description détaillée du poste",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "type_contrat",
        existing_type=postgresql.ENUM(
            "CDI", "CDD", "Stage", "Alternance", "Freelance", name="type_contrat"
        ),
        comment="Type de contrat proposé",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "localisation",
        existing_type=sa.VARCHAR(length=255),
        comment="Lieu de travail",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "salaire_min",
        existing_type=sa.INTEGER(),
        comment="Salaire minimum proposé",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "salaire_max",
        existing_type=sa.INTEGER(),
        comment="Salaire maximum proposé",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "statut",
        existing_type=postgresql.ENUM("brouillon", "publiee", "archivee", name="statut_offre"),
        comment="Statut de l'offre (brouillon, publiée, archivée)",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "date_publication",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date de publication de l'offre",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "reception_ouverte",
        existing_type=sa.BOOLEAN(),
        comment="Indique si l'offre accepte encore des candidatures",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "champs_personnalises_def",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Définition des champs personnalisés pour le formulaire",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "id",
        existing_type=sa.UUID(),
        comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "offres",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index("ix_offres_campagne_id", "offres", ["campagne_id"], unique=False)
    op.create_index("ix_offres_date_publication", "offres", ["date_publication"], unique=False)
    op.create_index(
        "ix_offres_search",
        "offres",
        [
            sa.literal_column(
                "to_tsvector('french', coalesce(titre, '') || ' ' || coalesce(description, ''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_offres_statut", "offres", ["statut"], unique=False)
    op.add_column(
        "utilisateurs",
        sa.Column("telephone", sa.String(length=50), nullable=True, comment="Numéro de téléphone"),
    )
    op.add_column(
        "utilisateurs",
        sa.Column(
            "fonction", sa.String(length=255), nullable=True, comment="Fonction ou poste occupé"
        ),
    )
    op.add_column(
        "utilisateurs",
        sa.Column(
            "email_verifie",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Indique si l'email a été vérifié",
        ),
    )
    op.add_column(
        "utilisateurs",
        sa.Column(
            "derniere_connexion",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date et heure de la dernière connexion",
        ),
    )
    op.add_column(
        "utilisateurs",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date et heure de la suppression logique",
        ),
    )
    op.add_column(
        "utilisateurs",
        sa.Column(
            "deleted_by",
            sa.UUID(),
            nullable=True,
            comment="ID de l'utilisateur qui a effectué la suppression",
        ),
    )
    op.alter_column(
        "utilisateurs",
        "entreprise_id",
        existing_type=sa.UUID(),
        comment="ID de l'entreprise de rattachement",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "nom",
        existing_type=sa.VARCHAR(length=255),
        comment="Nom complet de l'utilisateur",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Adresse email (unique)",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "mot_de_passe_hash",
        existing_type=sa.VARCHAR(length=255),
        comment="Hash du mot de passe",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "role",
        existing_type=postgresql.ENUM(
            "recruteur",
            "admin_rh",
            "admin_plateforme",
            "evaluateur_technique",
            name="role_utilisateur",
        ),
        comment="Rôle de l'utilisateur",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "actif",
        existing_type=sa.BOOLEAN(),
        comment="Indique si le compte est actif",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "id",
        existing_type=sa.UUID(),
        comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "utilisateurs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "ix_utilisateurs_email_verifie", "utilisateurs", ["email", "email_verifie"], unique=False
    )
    op.create_index(
        "ix_utilisateurs_entreprise_actif", "utilisateurs", ["entreprise_id", "actif"], unique=False
    )
    op.create_index(
        "ix_utilisateurs_entreprise_role", "utilisateurs", ["entreprise_id", "role"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_utilisateurs_entreprise_role", table_name="utilisateurs")
    op.drop_index("ix_utilisateurs_entreprise_actif", table_name="utilisateurs")
    op.drop_index("ix_utilisateurs_email_verifie", table_name="utilisateurs")
    op.alter_column(
        "utilisateurs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "utilisateurs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "utilisateurs",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "actif",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Indique si le compte est actif",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "role",
        existing_type=postgresql.ENUM(
            "recruteur",
            "admin_rh",
            "admin_plateforme",
            "evaluateur_technique",
            name="role_utilisateur",
        ),
        comment=None,
        existing_comment="Rôle de l'utilisateur",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "mot_de_passe_hash",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Hash du mot de passe",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Adresse email (unique)",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "nom",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Nom complet de l'utilisateur",
        existing_nullable=False,
    )
    op.alter_column(
        "utilisateurs",
        "entreprise_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="ID de l'entreprise de rattachement",
        existing_nullable=False,
    )
    op.drop_column("utilisateurs", "deleted_by")
    op.drop_column("utilisateurs", "deleted_at")
    op.drop_column("utilisateurs", "derniere_connexion")
    op.drop_column("utilisateurs", "email_verifie")
    op.drop_column("utilisateurs", "fonction")
    op.drop_column("utilisateurs", "telephone")
    op.drop_index("ix_offres_statut", table_name="offres")
    op.drop_index("ix_offres_search", table_name="offres", postgresql_using="gin")
    op.drop_index("ix_offres_date_publication", table_name="offres")
    op.drop_index("ix_offres_campagne_id", table_name="offres")
    op.alter_column(
        "offres",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "offres",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "offres",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "champs_personnalises_def",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="Définition des champs personnalisés pour le formulaire",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "reception_ouverte",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Indique si l'offre accepte encore des candidatures",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "date_publication",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date de publication de l'offre",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "statut",
        existing_type=postgresql.ENUM("brouillon", "publiee", "archivee", name="statut_offre"),
        comment=None,
        existing_comment="Statut de l'offre (brouillon, publiée, archivée)",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "salaire_max",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Salaire maximum proposé",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "salaire_min",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Salaire minimum proposé",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "localisation",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Lieu de travail",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "type_contrat",
        existing_type=postgresql.ENUM(
            "CDI", "CDD", "Stage", "Alternance", "Freelance", name="type_contrat"
        ),
        comment=None,
        existing_comment="Type de contrat proposé",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "description",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Description détaillée du poste",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "titre",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Titre de l'offre d'emploi",
        existing_nullable=False,
    )
    op.alter_column(
        "offres",
        "createur_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="ID de l'utilisateur créateur",
        existing_nullable=True,
    )
    op.alter_column(
        "offres",
        "campagne_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="ID de la campagne associée",
        existing_nullable=False,
    )
    op.drop_column("offres", "visible")
    op.drop_column("offres", "tele_travail")
    op.drop_column("offres", "avantages")
    op.drop_column("offres", "soft_skills")
    op.drop_column("offres", "missions")
    op.drop_index("ix_entreprises_statut", table_name="entreprises")
    op.drop_index("ix_entreprises_nom", table_name="entreprises")
    op.alter_column(
        "entreprises",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "entreprises",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "entreprises",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "entreprises",
        "logo_url",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="URL du logo de l'entreprise",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "adresse",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="Adresse de l'entreprise",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "taille",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Taille de l'entreprise (PME, Grand Groupe, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "secteur",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Secteur d'activité",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "domaine",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Domaine d'activité",
        existing_nullable=True,
    )
    op.alter_column(
        "entreprises",
        "nom",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Nom de l'entreprise",
        existing_nullable=False,
    )
    op.drop_column("entreprises", "motif_suspension")
    op.drop_column("entreprises", "statut")
    sa.Enum("active", "suspendue", name="statut_entreprise").drop(op.get_bind(), checkfirst=True)
    op.drop_column("entreprises", "description")
    op.drop_column("entreprises", "telephone")
    op.drop_column("entreprises", "site_web")
    op.drop_index("ix_candidatures_statut", table_name="candidatures")
    op.drop_index("ix_candidatures_offre_id", table_name="candidatures")
    op.drop_index("ix_candidatures_date_soumission", table_name="candidatures")
    op.drop_index("ix_candidatures_candidat_id", table_name="candidatures")
    op.alter_column(
        "candidatures",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "candidatures",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "candidatures",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "candidatures",
        "evaluation_ia",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="Évaluation détaillée générée par l'IA",
        existing_nullable=True,
    )
    op.alter_column(
        "candidatures",
        "score_global",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Score global calculé par l'IA (0-100)",
        existing_nullable=True,
    )
    op.alter_column(
        "candidatures",
        "champs_personnalises",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="Réponses aux champs personnalisés",
        existing_nullable=False,
    )
    op.alter_column(
        "candidatures",
        "cv_url",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="URL du CV du candidat",
        existing_nullable=True,
    )
    op.alter_column(
        "candidatures",
        "lettre_motivation",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Lettre de motivation du candidat",
        existing_nullable=True,
    )
    op.alter_column(
        "candidatures",
        "date_soumission",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de soumission",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "candidatures",
        "statut",
        existing_type=postgresql.ENUM(
            "recue",
            "en_cours_analyse",
            "preselectionnee",
            "test_technique",
            "entretien_rh",
            "entretien_metier",
            "verification_references",
            "decision",
            "offre_envoyee",
            "embauche",
            "refusee",
            "vivier_talents",
            name="statut_candidature",
        ),
        comment=None,
        existing_comment="Statut actuel de la candidature",
        existing_nullable=False,
    )
    op.alter_column(
        "candidatures",
        "candidat_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="ID du candidat associé",
        existing_nullable=False,
    )
    op.alter_column(
        "candidatures",
        "offre_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="ID de l'offre associée",
        existing_nullable=False,
    )
    op.drop_column("candidatures", "motif_refus")
    op.drop_column("candidatures", "decision_date")
    op.drop_column("candidatures", "entretien_notes")
    op.drop_column("candidatures", "evaluation_technique")
    op.drop_column("candidatures", "commentaires")
    op.drop_column("candidatures", "date_analyse")
    op.drop_index("ix_candidats_nom", table_name="candidats")
    op.drop_index("ix_candidats_email_verifie", table_name="candidats")
    op.alter_column(
        "candidats",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "candidats",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "candidats",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "candidats",
        "localisation",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Localisation géographique",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "annees_experience",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Nombre d'années d'expérience",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "titre_principal",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Titre ou poste actuel",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "telephone",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Numéro de téléphone",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "mot_de_passe_hash",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Hash du mot de passe (null si pas de compte)",
        existing_nullable=True,
    )
    op.alter_column(
        "candidats",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Adresse email (unique)",
        existing_nullable=False,
    )
    op.alter_column(
        "candidats",
        "nom",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Nom complet du candidat",
        existing_nullable=False,
    )
    op.drop_column("candidats", "deleted_by")
    op.drop_column("candidats", "deleted_at")
    op.drop_column("candidats", "permis_conduire")
    op.drop_column("candidats", "pret_a_relocaliser")
    op.drop_column("candidats", "preavis")
    op.drop_column("candidats", "disponibilite")
    op.drop_column("candidats", "portfolio_url")
    op.drop_column("candidats", "linkedin_url")
    op.drop_column("candidats", "email_verifie")
    op.drop_column("candidats", "cv_url")
    op.add_column(
        "campagnes",
        sa.Column("salaire", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "campagnes",
        sa.Column("experience", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.drop_index("ix_campagnes_statut", table_name="campagnes")
    op.drop_index("ix_campagnes_entreprise_id", table_name="campagnes")
    op.drop_index("ix_campagnes_date_limite", table_name="campagnes")
    op.alter_column(
        "campagnes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "campagnes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "campagnes",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "campagnes",
        "workflow",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="Workflow personnalisé de la campagne",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "type_contrat",
        existing_type=sa.Enum(
            "CDI", "CDD", "Stage", "Alternance", "Freelance", name="type_contrat"
        ),
        type_=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Type de contrat proposé",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "niveau_etudes",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Niveau d'études requis",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "langues",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
        comment=None,
        existing_comment="Langues requises",
        # Pas de sous-requête possible dans USING (Postgres l'interdit) : on
        # passe par la représentation texte du tableau JSON (["fr","en"]) et
        # on la retraduit en littéral de tableau Postgres ({fr,en}).
        postgresql_using="translate(langues::text, '[]\"', '{}')::varchar[]",
    )
    op.alter_column(
        "campagnes",
        "competences",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
        comment=None,
        existing_comment="Compétences requises",
        postgresql_using="translate(competences::text, '[]\"', '{}')::varchar[]",
    )
    op.alter_column(
        "campagnes",
        "localisation",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Localisation du poste",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "nombre_postes",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Nombre de postes à pourvoir",
        existing_nullable=False,
    )
    op.alter_column(
        "campagnes",
        "date_limite",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date limite de la campagne",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "departement",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Département ou service concerné",
        existing_nullable=True,
    )
    op.alter_column(
        "campagnes",
        "intitule",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Intitulé de la campagne",
        existing_nullable=False,
    )
    op.alter_column(
        "campagnes",
        "entreprise_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="ID de l'entreprise propriétaire",
        existing_nullable=False,
    )
    op.drop_column("campagnes", "statut")
    op.drop_column("campagnes", "description")
    op.drop_column("campagnes", "recruteurs_responsables")
    op.drop_column("campagnes", "salaire_max")
    op.drop_column("campagnes", "salaire_min")
    op.drop_column("campagnes", "experience_requise")
    op.alter_column(
        "abonnements",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de dernière modification",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "abonnements",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date et heure de création",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "abonnements",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Identifiant unique de l'enregistrement",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "date_fin",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date de fin de l'abonnement",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "date_debut",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Date de début de l'abonnement",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "statut",
        existing_type=postgresql.ENUM("actif", "expire", "essai", name="statut_abonnement"),
        comment=None,
        existing_comment="Statut de l'abonnement (actif, expire, essai)",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "plan",
        existing_type=postgresql.ENUM("starter", "business", "enterprise", name="plan_abonnement"),
        comment=None,
        existing_comment="Plan d'abonnement (starter, business, enterprise)",
        existing_nullable=False,
    )
    op.alter_column(
        "abonnements",
        "entreprise_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="ID de l'entreprise propriétaire de l'abonnement",
        existing_nullable=False,
    )
    op.drop_column("abonnements", "derniere_renouvellement")
    op.drop_column("abonnements", "renouvellement_auto")
    op.drop_index("ix_audit_logs_user_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_table_name", table_name="audit_logs")
    op.drop_index("ix_audit_logs_record_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
